### PR TITLE
enhancement(elm): Fetch resources on view change

### LINKED ISSUE #153: [UX/UI] Fetch data on view loading
**Type**

Enhancement

**Current behaviour**
We only fetch the room list once, forcing users to reload every time a new room is created (or number of players changes in specific rooms).

**Expected behaviour**
Fetch the data every time the room list view is loaded.

**Motivation / use case**
Essential for displaying current number of players in each room.

### PR DESCRIPTION
**Pull request by mrapacz**
**Summary**
This PR fetches room list every time the location is changed to `RoomListRoute`

I have also added a type alias for `Token = String`, so that the code gets more legible (I don't think I changed it everywhere though, only in the places I was dealing with). We may swap the type progressively.

**Related issues**
closes: #153 

**Test plan**
Watching requests (I removed the debug statements, you may run sha `ecae785` to test and see them)

### CODE REVIEW

**Comment by mrapacz** [comment]
I'm not sure if we should also remove the fetchRooms from init now.

**Comment by pmrukot** [comment]
We will need fetch on init when we make main view display rooms. (Scenario when user is logged in, token is stored in localStorage and user enters the page - first thing he sees is rooms and there is no action onLocationChange?)

**Comment by mrapacz** [comment]
@pmrukot nice catch, indeed, there will be no location change :+1:

**Review by pmrukot — APPROVED** [review]
Kudos for providing type alias for Token. Not sure about the wrappers that take whole model as an argument and how will it scale. Probably makes code slimmer for now but hard to tell what this will become after refactor.

**Comment by mrapacz** [comment]
The wrappers take the whole model because that's the way it looks currently in our Update.elm - everywhere where you send a request you would have to unwrap the token and take it from the model itself. 

The moment we split the Update to each of the modules we will probably keep the token in the contexts and then we will decide if there's a point in implementing such a function for each of the submodules (or maybe we will come up with a more generic one that would work everywhere).

**Pull request merged**
