### PR TITLE
enhancement(Docker): Improve image build process.

### PR DESCRIPTION
**Pull request by jtkpiotr**
**Summary**
Move parts like fetching and installing node js or pip to separate Dockerfile.
It should speed up building image process.

**Related issues**

**Test plan**

### CODE REVIEW

**Comment by mrapacz** [comment]
Do you think it's possible to move Elm out o the mix project folder to be in the root directory of the whole project? That would be the ideal solution imho. 

If not, I think it's better to actually leave it in aion/web/ (unless it somehow collides with the goal of this PR, if so, I'd like to know how).

**Comment by pmrukot** [comment]
Moving elm files currently makes no sense + I think it should be done in separate PR. It makes no sense because we still rely on phoenix template to render Elm application. When we will be able to separate this application to two services, one with pure phoenix server and one with elm app, then we can move the files.

**Comment by pmrukot** [comment]
@jtkpiotr Can we close this since we would like to extract Elm application as a separate frontend service? I do not consider having docker up to date with current local development scripts. We have different priorities now.

**Comment by mrapacz** [comment]
+1 to @pmrukot's suggestion

**Pull request closed without merging**
